service: dewais-task-backend
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-prune-plugin

custom:
  esbuild:
    bundle: true
    minify: false
    target: node18
    exclude: ['@aws-sdk']
    sourcemap: true
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  stage: dev
  memorySize: 128
  environment:
    NODE_OPTIONS: "--enable-source-maps"

functions:
  count-words:
    handler: src/lambdas/count-words/index.handler
    url:
      cors: true
